name: thedesigner
favicon: null
layout_spectrum: 0.5234562852419913
typography_spectrum: 0.9110140651464462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6676940396428108
  lightness: 0.4999963981099427
  saturation: 0.9085830925032496
  rhythmicContrast: 0.6426825518719852
purpose: []
